"""initial

Revision ID: d2ab551ec0a5
Revises: 
Create Date: 2026-05-29 16:58:31.686246

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd2ab551ec0a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corridors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_country', sa.String(length=3), nullable=False),
    sa.Column('source_currency', sa.String(length=3), nullable=False),
    sa.Column('collection_provider', sa.String(length=50), nullable=False),
    sa.Column('supported_methods', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('target_country', sa.String(length=3), nullable=False),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('disbursement_provider', sa.String(length=50), nullable=False),
    sa.Column('supported_targets', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('fee_type', sa.String(length=20), nullable=False),
    sa.Column('fee_percentage', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('fee_flat', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('min_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('min_transaction', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_transaction', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('daily_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corridors'))
    )
    op.create_index(op.f('ix_corridors_code'), 'corridors', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('kyc_status', sa.Enum('pending', 'submitted', 'verified', 'failed', name='kyc_status_enum'), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('fcm_token', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('waitlist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waitlist'))
    )
    op.create_index(op.f('ix_waitlist_created_at'), 'waitlist', ['created_at'], unique=False)
    op.create_index(op.f('ix_waitlist_email'), 'waitlist', ['email'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('corridor_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('source_currency', sa.String(length=3), nullable=False),
    sa.Column('source_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fee_percentage', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('collection_provider', sa.String(length=50), nullable=False),
    sa.Column('collection_method', sa.Enum('bank_transfer', 'card', 'ussd', 'mobile_money', name='collection_method_enum'), nullable=True),
    sa.Column('collection_reference', sa.String(length=255), nullable=True),
    sa.Column('collection_status', sa.Enum('pending', 'confirmed', 'failed', name='collection_status_enum'), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=14, scale=8), nullable=False),
    sa.Column('fx_rate_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('disbursement_provider', sa.String(length=50), nullable=False),
    sa.Column('disbursement_target_type', sa.String(length=50), nullable=False),
    sa.Column('disbursement_target_data', sa.Text(), nullable=False),
    sa.Column('disbursement_reference', sa.String(length=255), nullable=True),
    sa.Column('disbursement_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='disbursement_status_enum'), nullable=False),
    sa.Column('alipay_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'collection_initiated', 'collection_confirmed', 'disbursement_initiated', 'disbursement_processing', 'completed', 'failed', 'refund_initiated', 'refunded', name='tx_status_enum'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('refund_status', sa.Enum('none', 'initiated', 'completed', 'failed', name='refund_status_enum'), nullable=True),
    sa.Column('refund_reference', sa.String(length=255), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], name=op.f('fk_transactions_corridor_id_corridors')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('collection_reference', name=op.f('uq_transactions_collection_reference'))
    )
    op.create_index(op.f('ix_transactions_collection_status'), 'transactions', ['collection_status'], unique=False)
    op.create_index(op.f('ix_transactions_corridor_id'), 'transactions', ['corridor_id'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_disbursement_status'), 'transactions', ['disbursement_status'], unique=False)
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_audit_logs_transaction_id_transactions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_transaction_id'), 'audit_logs', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)

    # Seed initial corridor
    op.execute("""
              INSERT INTO corridors (
                  id, code, name, is_active,
                  source_country, source_currency, collection_provider, supported_methods,
                  target_country, target_currency, disbursement_provider, supported_targets,
                  fee_type, fee_percentage, fee_flat, min_fee, max_fee,
                  min_transaction, max_transaction, daily_limit,
                  created_at, updated_at
              ) VALUES (
                  gen_random_uuid(), 'NG-CN', 'Nigeria → China', true,
                  'NG', 'NGN', 'flutterwave', ARRAY['bank_transfer','card','ussd'],
                  'CN', 'CNY', 'lianlian', ARRAY['alipay_qr','wechat_qr'],
                  'percentage', 2.00, 0.00, 0.00, NULL,
                  5000.00, 5000000.00, 5000000.00,
                  now(), now()
              )
              ON CONFLICT (code) DO NOTHING;
          """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_transaction_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_disbursement_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_corridor_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_collection_status'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_waitlist_email'), table_name='waitlist')
    op.drop_index(op.f('ix_waitlist_created_at'), table_name='waitlist')
    op.drop_table('waitlist')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_corridors_code'), table_name='corridors')
    op.drop_table('corridors')
    # ### end Alembic commands ###
